export const COLORS = {
    PRIMARY_BLUE: '#40BFFF',
    PRIMARY_RED: '#FB7181',
    PRIMAR_YELLOW: '#FFC833',
    PRIMARY_GREEN:'#53D1B6',
    PRIMARY_PURPLE: '#5C61F4',

    NEUTRAL_DARK: '#223263',
    NEUTRAL_GREY: '#9098B1',
    NEUTRAL_LIGHT: '#EBF0FF',

    BACKGROUND_COLOR: '#FFFFFF'
}